In [1]:
import pandas as pd

In [2]:
df_train=pd.read_csv("YELP SA/yelp_review_fine-grained_5_classes_csv/train.csv")

In [3]:
len(df_train)

650000

In [4]:
df_train.head()

   class_index                                        review_text
0            5  dr. goldberg offers everything i look for in a...
1            2  Unfortunately, the frustration of being Dr. Go...
2            4  Been going to Dr. Goldberg for over 10 years. ...
3            4  Got a letter in the mail last week that said D...
4            1  I don't know what Dr. Goldberg was like before...

In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(df_train['review_text'])

In [6]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'i': 5,
 'to': 6,
 'was': 7,
 'of': 8,
 'it': 9,
 'for': 10,
 'in': 11,
 'n': 12,
 'is': 13,
 'that': 14,
 'my': 15,
 'but': 16,
 'we': 17,
 'this': 18,
 'with': 19,
 'they': 20,
 'you': 21,
 'on': 22,
 'not': 23,
 'have': 24,
 'had': 25,
 'at': 26,
 'were': 27,
 'so': 28,
 'are': 29,
 'food': 30,
 'good': 31,
 'be': 32,
 'place': 33,
 'there': 34,
 'as': 35,
 'me': 36,
 'like': 37,
 'out': 38,
 'just': 39,
 'if': 40,
 'all': 41,
 'very': 42,
 'here': 43,
 'our': 44,
 'get': 45,
 'one': 46,
 'or': 47,
 'time': 48,
 'up': 49,
 'when': 50,
 'great': 51,
 'from': 52,
 'would': 53,
 'service': 54,
 'their': 55,
 'about': 56,
 'go': 57,
 'back': 58,
 'really': 59,
 "it's": 60,
 'no': 61,
 'an': 62,
 'what': 63,
 'which': 64,
 'some': 65,
 'only': 66,
 'he': 67,
 'been': 68,
 'your': 69,
 'more': 70,
 'will': 71,
 'she': 72,
 'us': 73,
 'because': 74,
 'can': 75,
 'by': 76,
 "don't": 77,
 'got': 78,
 'even': 79,
 'them': 80,
 'other': 81,
 'nthe': 82,
 'do': 83,
 'too': 84,
 'also': 85,
 'after': 86,
 'nice': 87,
 'ni': 88,
 "didn't": 89,
 'ordered': 90,
 "i'm": 91,
 'well': 92,
 'than': 93,
 'did': 94,
 'has': 95,
 'much': 96,
 'order': 97,
 'people': 98,
 'over': 99,
 'came': 100,
 'could': 101,
 'went': 102,
 'little': 103,
 'restaurant': 104,
 'then': 105,
 'never': 106,
 'pretty': 107,
 'first': 108,
 'better': 109,
 'off': 110,
 'again': 111,
 "i've": 112,
 'said': 113,
 '2': 114,
 'best': 115,
 'know': 116,
 'try': 117,
 'chicken': 118,
 'way': 119,
 'her': 120,
 'going': 121,
 'two': 122,
 'how': 123,
 'menu': 124,
 'come': 125,
 'room': 126,
 'who': 127,
 'bar': 128,
 'night': 129,
 'think': 130,
 'love': 131,
 'make': 132,
 'always': 133,
 'staff': 134,
 'vegas': 135,
 'any': 136,
 'bad': 137,
 'before': 138,
 'want': 139,
 'made': 140,
 'down': 141,
 'minutes': 142,
 'experience': 143,
 'say': 144,
 '5': 145,
 'still': 146,
 'right': 147,
 '3': 148,
 'around': 149,
 'am': 150,
 'day': 151,
 'see': 152,
 'table': 153,
 'few': 154,
 "wasn't": 155,
 'take': 156,
 'wait': 157,
 'eat': 158,
 'friendly': 159,
 'give': 160,
 'told': 161,
 'asked': 162,
 'while': 163,
 'another': 164,
 'since': 165,
 'new': 166,
 'ever': 167,
 'took': 168,
 'sure': 169,
 'cheese': 170,
 'definitely': 171,
 'something': 172,
 'pizza': 173,
 'now': 174,
 'being': 175,
 'though': 176,
 'sauce': 177,
 'next': 178,
 'most': 179,
 'times': 180,
 'price': 181,
 'bit': 182,
 'into': 183,
 'where': 184,
 'thing': 185,
 'small': 186,
 'salad': 187,
 'lunch': 188,
 'find': 189,
 'meal': 190,
 'lot': 191,
 'nothing': 192,
 'drinks': 193,
 'last': 194,
 'many': 195,
 'long': 196,
 'his': 197,
 'everything': 198,
 'area': 199,
 'location': 200,
 'delicious': 201,
 'should': 202,
 'wanted': 203,
 '4': 204,
 'dinner': 205,
 'its': 206,
 'ok': 207,
 'every': 208,
 '1': 209,
 'side': 210,
 'fresh': 211,
 'stars': 212,
 'check': 213,
 "can't": 214,
 '10': 215,
 'big': 216,
 'hotel': 217,
 'drink': 218,
 'same': 219,
 'hot': 220,
 'burger': 221,
 'amazing': 222,
 'tried': 223,
 'hour': 224,
 'enough': 225,
 'looking': 226,
 'both': 227,
 "you're": 228,
 'worth': 229,
 'need': 230,
 'work': 231,
 'left': 232,
 'server': 233,
 'taste': 234,
 'why': 235,
 'away': 236,
 'things': 237,
 'fries': 238,
 "that's": 239,
 'home': 240,
 'store': 241,
 'prices': 242,
 'different': 243,
 'feel': 244,
 'actually': 245,
 'thought': 246,
 'quality': 247,
 'free': 248,
 'happy': 249,
 'however': 250,
 'probably': 251,
 'customer': 252,
 'meat': 253,
 'anything': 254,
 'maybe': 255,
 'old': 256,
 'him': 257,
 'recommend': 258,
 'nwe': 259,
 'line': 260,
 'flavor': 261,
 'sushi': 262,
 'sandwich': 263,
 'these': 264,
 'friends': 265,
 'look': 266,
 'found': 267,
 'else': 268,
 'once': 269,
 'decided': 270,
 'places': 271,
 'special': 272,
 'money': 273,
 'beer': 274,
 'looked': 275,
 'awesome': 276,
 'called': 277,
 'clean': 278,
 'top': 279,
 'half': 280,
 'visit': 281,
 'ask': 282,
 'full': 283,
 'put': 284,
 'kind': 285,
 'review': 286,
 'bread': 287,
 'decent': 288,
 'pay': 289,
 'breakfast': 290,
 'getting': 291,
 'front': 292,
 'sweet': 293,
 'friend': 294,
 'quite': 295,
 'rice': 296,
 'least': 297,
 'show': 298,
 'years': 299,
 'through': 300,
 'used': 301,
 'water': 302,
 'steak': 303,
 'done': 304,
 'manager': 305,
 'waitress': 306,
 'coffee': 307,
 'strip': 308,
 'those': 309,
 'each': 310,
 'star': 311,
 'inside': 312,
 'fried': 313,
 'super': 314,
 'dish': 315,
 'tasty': 316,
 'selection': 317,
 'huge': 318,
 '20': 319,
 'stay': 320,
 'large': 321,
 'favorite': 322,
 'car': 323,
 'high': 324,
 'tasted': 325,
 "i'd": 326,
 'hard': 327,
 'buffet': 328,
 'open': 329,
 'almost': 330,
 'beef': 331,
 'couple': 332,
 'finally': 333,
 '30': 334,
 'call': 335,
 'waiting': 336,
 'without': 337,
 'atmosphere': 338,
 'gave': 339,
 'business': 340,
 'let': 341,
 'use': 342,
 'soup': 343,
 'seemed': 344,
 'having': 345,
 'fun': 346,
 'far': 347,
 'disappointed': 348,
 'someone': 349,
 'excellent': 350,
 'outside': 351,
 'tables': 352,
 'served': 353,
 'busy': 354,
 'reviews': 355,
 "i'll": 356,
 'three': 357,
 'tell': 358,
 'end': 359,
 'items': 360,
 'part': 361,
 'house': 362,
 'coming': 363,
 'later': 364,
 "couldn't": 365,
 'trying': 366,
 'person': 367,
 'everyone': 368,
 'wine': 369,
 'eating': 370,
 'fish': 371,
 'less': 372,
 'usually': 373,
 'whole': 374,
 'town': 375,
 'cool': 376,
 '15': 377,
 'hours': 378,
 'cooked': 379,
 'wrong': 380,
 'guy': 381,
 'during': 382,
 'husband': 383,
 'either': 384,
 'until': 385,
 'waiter': 386,
 'cream': 387,
 'dishes': 388,
 'care': 389,
 'walked': 390,
 'walk': 391,
 "won't": 392,
 '6': 393,
 'instead': 394,
 'restaurants': 395,
 'such': 396,
 "isn't": 397,
 'felt': 398,
 'shrimp': 399,
 'cold': 400,
 "doesn't": 401,
 'music': 402,
 'close': 403,
 'pork': 404,
 'family': 405,
 'does': 406,
 'okay': 407,
 'perfect': 408,
 'must': 409,
 'point': 410,
 'door': 411,
 'enjoy': 412,
 'plate': 413,
 'deal': 414,
 'extra': 415,
 'brought': 416,
 'second': 417,
 'may': 418,
 'course': 419,
 'especially': 420,
 'spot': 421,
 'needed': 422,
 'week': 423,
 'cheap': 424,
 'waited': 425,
 'guess': 426,
 "wouldn't": 427,
 'ice': 428,
 'several': 429,
 'party': 430,
 'overall': 431,
 'fine': 432,
 'fast': 433,
 'dessert': 434,
 'might': 435,
 'dining': 436,
 'reason': 437,
 'spicy': 438,
 'started': 439,
 'nmy': 440,
 'arrived': 441,
 'saw': 442,
 'shop': 443,
 'own': 444,
 'year': 445,
 'enjoyed': 446,
 'expect': 447,
 'oh': 448,
 'yes': 449,
 "there's": 450,
 'worst': 451,
 'sat': 452,
 'days': 453,
 'dry': 454,
 'group': 455,
 'help': 456,
 'sit': 457,
 'loved': 458,
 'keep': 459,
 'parking': 460,
 'quick': 461,
 'name': 462,
 'seated': 463,
 'bring': 464,
 'comes': 465,
 'rude': 466,
 'red': 467,
 'horrible': 468,
 'able': 469,
 'chocolate': 470,
 'stop': 471,
 'yelp': 472,
 'return': 473,
 'plus': 474,
 'leave': 475,
 'kids': 476,
 'makes': 477,
 'problem': 478,
 'seems': 479,
 'customers': 480,
 'wife': 481,
 'expensive': 482,
 'fact': 483,
 'job': 484,
 'floor': 485,
 'average': 486,
 '8': 487,
 'slow': 488,
 'options': 489,
 'chips': 490,
 'club': 491,
 'although': 492,
 'pool': 493,
 '7': 494,
 'stuff': 495,
 'rooms': 496,
 'real': 497,
 'yet': 498,
 'las': 499,
 'myself': 500,
 'late': 501,
 'already': 502,
 'liked': 503,
 'owner': 504,
 'paid': 505,
 'fan': 506,
 'phone': 507,
 'cut': 508,
 'rather': 509,
 'bill': 510,
 'start': 511,
 'ate': 512,
 'tea': 513,
 '50': 514,
 'extremely': 515,
 'terrible': 516,
 'drive': 517,
 'offer': 518,
 'style': 519,
 'size': 520,
 'roll': 521,
 'casino': 522,
 'ended': 523,
 'today': 524,
 'anyone': 525,
 'live': 526,
 'ago': 527,
 'street': 528,
 'mexican': 529,
 'seem': 530,
 'decor': 531,
 'working': 532,
 'guys': 533,
 'bacon': 534,
 'trip': 535,
 'tacos': 536,
 'absolutely': 537,
 'bland': 538,
 'rolls': 539,
 'buy': 540,
 'lots': 541,
 'local': 542,
 'nthis': 543,
 'given': 544,
 'wish': 545,
 'sitting': 546,
 'doing': 547,
 'kitchen': 548,
 'charge': 549,
 'card': 550,
 'thai': 551,
 'etc': 552,
 'regular': 553,
 'hair': 554,
 'past': 555,
 'making': 556,
 'seen': 557,
 'short': 558,
 'mind': 559,
 "they're": 560,
 'pick': 561,
 'counter': 562,
 'helpful': 563,
 'amount': 564,
 'looks': 565,
 'impressed': 566,
 'bbq': 567,
 'under': 568,
 'green': 569,
 'non': 570,
 'fantastic': 571,
 'crab': 572,
 'white': 573,
 'run': 574,
 'wonderful': 575,
 'completely': 576,
 'portions': 577,
 'between': 578,
 'morning': 579,
 'girl': 580,
 'burgers': 581,
 'wings': 582,
 'dog': 583,
 'believe': 584,
 'tip': 585,
 'ready': 586,
 'change': 587,
 'cake': 588,
 'saturday': 589,
 'entire': 590,
 'set': 591,
 'heard': 592,
 "weren't": 593,
 'main': 594,
 'empty': 595,
 'chinese': 596,
 'twice': 597,
 'serve': 598,
 'kept': 599,
 'light': 600,
 'gone': 601,
 'itself': 602,
 'seating': 603,
 'priced': 604,
 'quickly': 605,
 'glass': 606,
 'employees': 607,
 'mean': 608,
 'gets': 609,
 'early': 610,
 '00': 611,
 'salsa': 612,
 'list': 613,
 'man': 614,
 'easy': 615,
 'rest': 616,
 'remember': 617,
 'poor': 618,
 'four': 619,
 'egg': 620,
 'warm': 621,
 'choice': 622,
 'lady': 623,
 'nso': 624,
 'behind': 625,
 'potatoes': 626,
 'eggs': 627,
 'nif': 628,
 'nthey': 629,
 'de': 630,
 'appetizer': 631,
 'soon': 632,
 'expected': 633,
 'understand': 634,
 'taking': 635,
 'highly': 636,
 'weekend': 637,
 'french': 638,
 'view': 639,
 'stayed': 640,
 'received': 641,
 'beautiful': 642,
 'offered': 643,
 'needs': 644,
 'hit': 645,
 'walking': 646,
 'seriously': 647,
 'patio': 648,
 'near': 649,
 'across': 650,
 '12': 651,
 'la': 652,
 'potato': 653,
 'pasta': 654,
 'attentive': 655,
 'often': 656,
 'stopped': 657,
 'type': 658,
 'cost': 659,
 'desk': 660,
 'company': 661,
 'others': 662,
 'bite': 663,
 'flavors': 664,
 'portion': 665,
 'available': 666,
 'italian': 667,
 'plenty': 668,
 'saying': 669,
 '9': 670,
 'knew': 671,
 'ordering': 672,
 'hand': 673,
 'totally': 674,
 'orders': 675,
 'variety': 676,
 'life': 677,
 'add': 678,
 'beans': 679,
 'months': 680,
 'unfortunately': 681,
 'sandwiches': 682,
 'phoenix': 683,
 "you'll": 684,
 'watch': 685,
 'dirty': 686,
 'loud': 687,
 'sorry': 688,
 'bowl': 689,
 'paying': 690,
 'garlic': 691,
 'due': 692,
 'sunday': 693,
 'reasonable': 694,
 'evening': 695,
 'bartender': 696,
 'sign': 697,
 'please': 698,
 'read': 699,
 'along': 700,
 'packed': 701,
 'overpriced': 702,
 'game': 703,
 'spend': 704,
 'servers': 705,
 'grilled': 706,
 'noticed': 707,
 'friday': 708,
 'head': 709,
 'yummy': 710,
 'noverall': 711,
 '25': 712,
 'space': 713,
 'black': 714,
 'giving': 715,
 'unless': 716,
 'none': 717,
 'idea': 718,
 'office': 719,
 'mediocre': 720,
 'chef': 721,
 'taco': 722,
 'perfectly': 723,
 'simple': 724,
 'girls': 725,
 'sometimes': 726,
 'located': 727,
 'taken': 728,
 'bathroom': 729,
 'five': 730,
 'eaten': 731,
 'number': 732,
 'nit': 733,
 'seafood': 734,
 'comfortable': 735,
 'birthday': 736,
 'crowd': 737,
 'lobster': 738,
 'hungry': 739,
 'middle': 740,
 'pieces': 741,
 'excited': 742,
 'hope': 743,
 'surprised': 744,
 'ones': 745,
 'together': 746,
 'butter': 747,
 'literally': 748,
 'low': 749,
 'says': 750,
 'based': 751,
 'crispy': 752,
 'minute': 753,
 'city': 754,
 'checked': 755,
 'talk': 756,
 'medium': 757,
 'opened': 758,
 'wow': 759,
 'salmon': 760,
 'choose': 761,
 'boyfriend': 762,
 'oil': 763,
 'closed': 764,
 'longer': 765,
 'awful': 766,
 'piece': 767,
 'yourself': 768,
 'pricey': 769,
 'noodles': 770,
 "haven't": 771,
 'per': 772,
 'cup': 773,
 'bottle': 774,
 'spent': 775,
 'beers': 776,
 'seat': 777,
 'turned': 778,
 'salty': 779,
 'bought': 780,
 'crowded': 781,
 'total': 782,
 'reservation': 783,
 '40': 784,
 'weeks': 785,
 'plates': 786,
 'hostess': 787,
 'issue': 788,
 'talking': 789,
 'onion': 790,
 'prepared': 791,
 'disappointing': 792,
 'hear': 793,
 'feeling': 794,
 'immediately': 795,
 'standard': 796,
 'ingredients': 797,
 'bed': 798,
 'credit': 799,
 'frozen': 800,
 'w': 801,
 'happened': 802,
 "aren't": 803,
 'interesting': 804,
 'park': 805,
 'brunch': 806,
 'charged': 807,
 'burrito': 808,
 'cafe': 809,
 'except': 810,
 'ambiance': 811,
 'mall': 812,
 'exactly': 813,
 '45': 814,
 'choices': 815,
 'center': 816,
 'option': 817,
 'case': 818,
 'month': 819,
 'including': 820,
 'within': 821,
 'play': 822,
 'pho': 823,
 'moved': 824,
 'world': 825,
 'recently': 826,
 'shopping': 827,
 'thank': 828,
 'goes': 829,
 'somewhere': 830,
 'glad': 831,
 'chance': 832,
 'stand': 833,
 'basically': 834,
 'appetizers': 835,
 'filled': 836,
 '99': 837,
 '11': 838,
 'specials': 839,
 'appointment': 840,
 'management': 841,
 'asian': 842,
 'meals': 843,
 'staying': 844,
 'weird': 845,
 'simply': 846,
 'mac': 847,
 'hate': 848,
 'cute': 849,
 'wall': 850,
 'added': 851,
 'whatever': 852,
 'upon': 853,
 'thanks': 854,
 'honestly': 855,
 'asking': 856,
 'anyway': 857,
 'sort': 858,
 'crust': 859,
 'tiny': 860,
 'nservice': 861,
 'scottsdale': 862,
 'supposed': 863,
 'rib': 864,
 'flavorful': 865,
 'soft': 866,
 'miss': 867,
 'dark': 868,
 'salt': 869,
 'takes': 870,
 'sausage': 871,
 'above': 872,
 'mouth': 873,
 'anywhere': 874,
 'tuna': 875,
 'pleasant': 876,
 'mention': 877,
 'tomato': 878,
 'u00e9': 879,
 'sides': 880,
 'greasy': 881,
 'lack': 882,
 'level': 883,
 'dance': 884,
 'attention': 885,
 'kinda': 886,
 'fix': 887,
 'worse': 888,
 'move': 889,
 '100': 890,
 'nwhen': 891,
 'write': 892,
 'thin': 893,
 'hands': 894,
 'date': 895,
 'typical': 896,
 'curry': 897,
 'attitude': 898,
 'mine': 899,
 'expecting': 900,
 'changed': 901,
 'finish': 902,
 'downtown': 903,
 'box': 904,
 'sad': 905,
 'tender': 906,
 'ribs': 907,
 'airport': 908,
 'apparently': 909,
 'bucks': 910,
 'seats': 911,
 'authentic': 912,
 'thinking': 913,
 'crazy': 914,
 'tv': 915,
 'joint': 916,
 'recommended': 917,
 'waste': 918,
 'lost': 919,
 'lettuce': 920,
 'section': 921,
 'note': 922,
 'corn': 923,
 'fairly': 924,
 'tasting': 925,
 'unique': 926,
 'dressing': 927,
 'serving': 928,
 'entrees': 929,
 'mixed': 930,
 'worked': 931,
 'certainly': 932,
 'showed': 933,
 'face': 934,
 'rating': 935,
 'eye': 936,
 'onions': 937,
 'fair': 938,
 'barely': 939,
 'mix': 940,
 'item': 941,
 'cook': 942,
 'slightly': 943,
 'avoid': 944,
 'cash': 945,
 'save': 946,
 'salads': 947,
 'nfor': 948,
 'forward': 949,
 'running': 950,
 'value': 951,
 'single': 952,
 'entree': 953,
 'share': 954,
 'bag': 955,
 'playing': 956,
 'considering': 957,
 'dollars': 958,
 'nas': 959,
 'rare': 960,
 'online': 961,
 'finished': 962,
 'greeted': 963,
 'station': 964,
 'nthere': 965,
 'book': 966,
 'toppings': 967,
 'turn': 968,
 'veggies': 969,
 'desserts': 970,
 'mostly': 971,
 'school': 972,
 'toast': 973,
 'opinion': 974,
 'b': 975,
 'yeah': 976,
 'cannot': 977,
 'forgot': 978,
 'young': 979,
 'delivery': 980,
 'chain': 981,
 'woman': 982,
 'obviously': 983,
 'grab': 984,
 'mentioned': 985,
 'tastes': 986,
 'picked': 987,
 'sent': 988,
 'm': 989,
 'included': 990,
 'elsewhere': 991,
 'pass': 992,
 'clearly': 993,
 'd': 994,
 'afternoon': 995,
 'dogs': 996,
 'professional': 997,
 'min': 998,
 'watching': 999,
 'massage': 1000,
 ...}

In [7]:
tokenizer.word_counts

OrderedDict([('dr', 8635),
             ('goldberg', 15),
             ('offers', 5817),
             ('everything', 61910),
             ('i', 2253626),
             ('look', 43611),
             ('for', 1022360),
             ('in', 1002595),
             ('a', 2254526),
             ('general', 7757),
             ('practitioner', 141),
             ("he's", 5875),
             ('nice', 136628),
             ('and', 2783872),
             ('easy', 17389),
             ('to', 2166248),
             ('talk', 13184),
             ('without', 35418),
             ('being', 69966),
             ('patronizing', 278),
             ('always', 91843),
             ('on', 621465),
             ('time', 248911),
             ('seeing', 9191),
             ('his', 62182),
             ('patients', 1439),
             ('affiliated', 241),
             ('with', 670069),
             ('top', 42003),
             ('notch', 5287),
             ('hospital', 2645),
             ('nyu', 13),
             ('which', 193881),
             ('my', 746238),
             ('parents', 4534),
             ('have', 540331),
             ('explained', 7972),
             ('me', 338236),
             ('is', 984978),
             ('very', 279774),
             ('important', 5391),
             ('case', 12123),
             ('something', 71040),
             ('happens', 4360),
             ('you', 625690),
             ('need', 51758),
             ('surgery', 1478),
             ('can', 165274),
             ('get', 274388),
             ('referrals', 143),
             ('see', 81215),
             ('specialists', 145),
             ('having', 34882),
             ('him', 45506),
             ('first', 110126),
             ('really', 210066),
             ('what', 199592),
             ('more', 175235),
             ('do', 144059),
             ("i'm", 127593),
             ('sitting', 20629),
             ('here', 279494),
             ('trying', 32769),
             ('think', 93391),
             ('of', 1319566),
             ('any', 88616),
             ('complaints', 5680),
             ('about', 225097),
             ('but', 731268),
             ('drawing', 346),
             ('blank', 718),
             ('unfortunately', 15415),
             ('the', 4374545),
             ('frustration', 1016),
             ("goldberg's", 3),
             ('patient', 4391),
             ('repeat', 3153),
             ('experience', 85231),
             ("i've", 104831),
             ('had', 509175),
             ('so', 453060),
             ('many', 62754),
             ('other', 152915),
             ('doctors', 1593),
             ('nyc', 2480),
             ('good', 391996),
             ('doctor', 5013),
             ('terrible', 22291),
             ('staff', 91209),
             ('it', 1161758),
             ('seems', 24411),
             ('that', 821833),
             ('simply', 11554),
             ('never', 114496),
             ('answers', 1228),
             ('phone', 22822),
             ('usually', 31922),
             ('takes', 11143),
             ('2', 103460),
             ('hours', 31242),
             ('repeated', 1092),
             ('calling', 5048),
             ('an', 209169),
             ('answer', 6130),
             ('who', 95203),
             ('has', 122544),
             ('or', 252819),
             ('wants', 4657),
             ('deal', 28394),
             ('run', 18740),
             ('into', 66833),
             ('this', 674062),
             ('problem', 24472),
             ('just', 311120),
             ("don't", 158193),
             ('office', 14254),
             ('workers', 6072),
             ('medical', 1789),
             ('needs', 16665),
             ('why', 50326),
             ("isn't", 30071),
             ('anyone', 21764),
             ('answering', 1042),
             ("it's", 209871),
             ('incomprehensible', 37),
             ('not', 598489),
             ('work', 51496),
             ('aggravation', 179),
             ('regret', 2809),
             ('feel', 48282),
             ('give', 76070),
             ('stars', 57253),
             ('been', 176253),
             ('going', 97755),
             ('over', 119735),
             ('10', 56835),
             ('years', 39730),
             ('was', 1583476),
             ('one', 272078),
             ('1st', 3213),
             ('when', 245621),
             ('he', 177876),
             ('started', 26665),
             ('at', 487624),
             ('mhmg', 1),
             ('great', 242634),
             ('all', 304028),
             ('big', 56701),
             ('picture', 5818),
             ('because', 167238),
             ('now', 70511),
             ('former', 1858),
             ('gyn', 69),
             ('markoff', 3),
             ('found', 42994),
             ('out', 314155),
             ('fibroids', 4),
             ('explores', 11),
             ('options', 23925),
             ('understanding', 1751),
             ("doesn't", 29698),
             ('judge', 2195),
             ('asks', 2444),
             ('right', 83117),
             ('questions', 7919),
             ('thorough', 1451),
             ('be', 382525),
             ('kept', 17776),
             ('loop', 542),
             ('every', 58115),
             ('aspect', 1356),
             ('your', 175754),
             ('health', 4253),
             ('life', 15559),
             ('got', 155968),
             ('letter', 1297),
             ('mail', 2758),
             ('last', 62806),
             ('week', 27783),
             ('said', 103689),
             ('moving', 6170),
             ('arizona', 6109),
             ('take', 78902),
             ('new', 73432),
             ('position', 944),
             ('there', 357139),
             ('june', 1324),
             ('will', 172831),
             ('missed', 4830),
             ('much', 122163),
             ('n', 989631),
             ('ni', 136461),
             ('finding', 5648),
             ('actually', 48237),
             ('like', 317609),
             ('might', 27159),
             ('almost', 35877),
             ('as', 350109),
             ('awful', 12961),
             ('find', 63926),
             ('date', 10820),
             ('know', 102806),
             ('before', 87645),
             ('let', 35283),
             ('tell', 33647),
             ('stay', 37403),
             ('away', 50163),
             ('from', 242630),
             ('johnson', 236),
             ('left', 51034),
             ('took', 72794),
             ('caring', 1471),
             ('only', 179008),
             ('interested', 4694),
             ('co', 4917),
             ('pay', 40349),
             ('come', 95422),
             ('medication', 709),
             ('refills', 5214),
             ('month', 12121),
             ('could', 117645),
             ('less', 31944),
             ("patients's", 1),
             ('financial', 524),
             ('situations', 427),
             ('90', 3957),
             ('days', 25789),
             ('pharmacy', 1386),
             ('prescriptions', 461),
             ('through', 39697),
             ('guy', 31137),
             ('joke', 5798),
             ('make', 92795),
             ('matters', 1249),
             ('even', 155461),
             ('worse', 10926),
             ('incompetent', 1236),
             ('call', 35558),
             ("they'll", 3527),
             ('put', 41218),
             ('voice', 2435),
             ('no', 209587),
             ('ever', 73313),
             ('returns', 908),
             ('both', 52732),
             ('adult', 2722),
             ('children', 5126),
             ('husband', 31030),
             ('decided', 42605),
             ('leave', 24575),
             ('practice', 2635),
             ('after', 141314),
             ('experiencing', 717),
             ('such', 30084),
             ('entire', 18012),
             ('attitude', 10758),
             ('they', 644973),
             ('are', 400362),
             ('doing', 20615),
             ('favor', 3875),
             ('break', 7585),
             ('doc', 496),
             ('deserve', 2641),
             ('better', 109584),
             ('them', 154557),
             ('felt', 30060),
             ('compelled', 610),
             ('write', 10872),
             ('bad', 87961),
             ('review', 40572),
             ('until', 30919),
             ('met', 6807),
             ('pathetic', 1540),
             ('excuse', 4897),
             ('money', 42407),
             ("can't", 56850),
             ('say', 84958),
             ('am', 81922),
             ('surprised', 13507),
             ('referred', 1364),
             ('by', 159784),
             ('another', 74896),
             ('wonderful', 18736),
             ('went', 117334),
             ('best', 103024),
             ('schools', 284),
             ('country', 5696),
             ('nit', 13705),
             ('appointment', 11659),
             ('minimal', 1725),
             ('wait', 78440),
             ('seen', 19917),
             ('bedside', 313),
             ('manner', 2727),
             ('eric', 692),
             ('fantastic', 18929),
             ('correctly', 2854),
             ('diagnosed', 403),
             ('issue', 12635),
             ('wife', 24319),
             ('unlike', 3581),
             ('past', 19954),
             ('accessible', 1007),
             ('we', 683585),
             ('able', 24898),
             ('schedule', 3665),
             ('appointments', 1732),
             ('quickly', 17680),
             ('happy', 47712),
             ('neighborhood', 8441),
             ('forward', 10032),
             ('writing', 4498),
             ('heads', 2222),
             ('up', 247357),
             ('administration', 106),
             ('unprofessional', 3908),
             ('message', 2890),
             ('multiple', 7020),
             ('people', 120250),
             ('regarding', 1905),
             ('bill', 22641),
             ('called', 42167),
             ('back', 219151),
             ('hound', 250),
             ('nsecond', 1302),
             ('most', 68391),
             ('sure', 72784),
             ('insurance', 4758),
             ('cover', 7301),
             ('visits', 5611),
             ('blood', 2906),
             ('recommended', 10508),
             ('physical', 835),
             ('knew', 15657),
             ('student', 2558),
             ('told', 76023),
             ('done', 39410),
             ('later', 32831),
             ('preventative', 57),
             ('received', 16894),
             ('800', 883),
             ('00', 17500),
             ('cash', 10070),
             ('flow', 1254),
             ('current', 2402),
             ('believe', 18284),
             ("wouldn't", 27653),
             ('would', 242344),
             ("wasn't", 78913),
             ('necessary', 2465),
             ('strictly', 799),
             ('anything', 46928),
             ('help', 25606),
             ('addition', 6500),
             ('onus', 9),
             ('covers', 1272),
             ('frustrating', 2119),
             ('situation', 7037),
             ('wing', 2643),
             ('sauce', 69366),
             ('water', 39460),
             ('pretty', 112783),
             ('lot', 63334),
             ('butter', 13492),
             ('some', 193072),
             ('hot', 54523),
             ('franks', 112),
             ('red', 24965),
             ('maybe', 46476),
             ('whole', 31860),
             ('wings', 18552),
             ('size', 22005),
             ('crispy', 13319),
             ('1', 58015),
             ('extra', 28228),
             ('same', 54819),
             ('flavor', 44525),
             ('heat', 7978),
             ('fish', 31980),
             ('sandwich', 44095),
             ('large', 37312),
             ('portion', 15950),
             ('sides', 10990),
             ('decent', 40486),
             ('range', 5907),
             ('somewhat', 7254),
             ('close', 29377),
             ('city', 13289),
             ('mats', 467),
             ('solid', 8537),
             ('however', 47705),
             ('grass', 1597),
             ('tended', 331),
             ('too', 143516),
             ('hitting', 1629),
             ('us', 170550),
             ('open', 36140),
             ('type', 16213),
             ('rough', 2089),
             ('amenable', 31),
             ('practicing', 228),
             ('kind', 41116),
             ('defeats', 178),
             ('purpose', 1862),
             ('golf', 2615),
             ('still', 83995),
             ('gets', 17528),
             ('3', 82843),
             ('lit', 2743),
             ('night', 93476),
             ('excellent', 34220),
             ('those', 38756),
             ('addicted', 779),
             ('amazing', 54062),
             ('game', 14632),
             ('short', 19881),
             ('job', 24199),
             ('kinda', 10935),
             ('sucks', 7131),
             ('sometimes', 13946),
             ('owning', 164),
             ('driving', 5974),
             ('inside', 38132),
             ('limits', 547),
             ('license', 1449),
             ('print', 2225),
             ('ask', 41226),
             ('clean', 42161),
             ('balls', 3526),
             ('hell', 7649),
             ('advent', 26),
             ('machine', 7282),
             ('doles', 8),
             ('place', 379285),
             ('none', 14269),
             ('april', 1307),
             ('tees', 172),
             ('yet', 23318),
             ('btw', 2331),
             ('opened', 13166),
             ('season', 3546),
             ('although', 23785),
             ('golfing', 144),
             ('weather', 4089),
             ('carpet', 3725),
             ('107', 171),
             ('year', 26323),
             ('old', 45712),
             ('aunt', 836),
             ("irene's", 9),
             ('house', 32978),
             ('worn', 1735),
             ('thread', 304),
             ('bare', 1358),
             ("let's", 6176),
             ('equipped', 633),
             ('lights', 5641),
             ('sell', 8320),
             ('buckets', 411),
             ('730', 136),
             ('light', 17760),
             ('finally', 35697),
             ('lets', 2711),
             ('pit', 1835),
             ('hit', 16574),
             ('arrived', 26395),
             ('if', 309383),
             ('excavation', 3),
             ('site', 4008),
             ('mastodon', 2),
             ('strip', 38813),
             ('mining', 49),
             ('operation', 1034),
             ('mud', 348),
             ('makes', 24514),
             ('tool', 538),
             ('figure', 6229),
             ('how', 96061),
             ('far', 34348),
             ('ball', 3644),
             ('oh', 26045),
             ('also', 142681),
             ('nbottom', 1562),
             ('line', 44790),
             ('hope', 13518),
             ('owner', 22952),
             ('sells', 1337),
             ('someone', 34253),
             ('service', 238568),
             ('golfers', 133),
             ('pittsburgh', 6044),
             ('absolute', 3600),
             ('garbage', 2423),
             ('half', 41892),
             ('available', 15945),
             ('including', 12112),
             ('bucket', 1481),
             ('8', 23985),
             ('despite', 8313),
             ('finish', 10703),
             ('minute', 13302),
             ('plan', 8720),
             ('getting', 40337),
             ('drink', 56225),
             ('vending', 453),
             ('machines', 5609),
             ('sold', 5079),
             ('course', 27910),
             ('drinks', 62888),
             ('drawers', 277),
             ('dot', 384),
             ('weeds', 199),
             ('grown', 1636),
             ('noticed', 14523),
             ('sort', 11333),
             ('batting', 164),
             ('cage', 504),
             ('looks', 19399),
             ('order', 120616),
             ('well', 127216),
             ('should', 60457),
             ('buy', 21016),
             ('turn', 9792),
             ('drove', 4792),
             ('yesterday', 5329),
             ('sneak', 515),
             ('peak', 1865),
             ('re', 4998),
             ('opens', 1504),
             ('july', 2212),
             ('14th', 168),
             ('kids', 24528),
             ('appears', 2300),
             ('turf', 936),
             ('may', 27978),
             ('tee', 879),
             ('boxes', 2780),
             ('state', 5446),
             ('art', 5665),
             ('club', 23848),
             ("you'll", 15347),
             ('newer', 1753),
             ('waiting', 35509),
             ('30', 35680),
             ('minutes', 85643),
             ('trade', 1606),
             ('part', 33183),
             ('program', 1864),
             ('our', 277402),
             ('customer', 47273),
             ('rep', 1586),
             ('incorrectly', 663),
             ('processed', 1280),
             ('transaction', 1108),
             ('led', 1911),
             ('correct', 5474),
             ('visit', 41252),
             ('store', 48779),
             ('want', 87215),
             ('pleasant', 11056),
             ('delicious', 60932),
             ('saw', 26381),
             ('recommendation', 3762),
             ('rick', 634),
             ("sebak's", 2),
             ('25', 14372),
             ('things', 49710),
             ('accurate', 1296),
             ('recommendations', 2893),
             ('were', 482386),
             ('try', 100274),
             ('reuben', 981),
             ('faced', 869),
             ('steak', 39419),
             ('early', 17505),
             ('afternoon', 9468),
             ('late', 23255),
             ('lunch', 64022),
             ('today', 21800),
             ('saturday', 18022),
             ('seated', 25377),
             ('extremely', 22296),
             ('friendly', 76846),
             ('mom', 9130),
             ('each', 38623),
             ('while', 75499),
             ('dad', 3466),
             ('brother', 3342),
             ('die', 8978),
             ('dishes', 30696),
             ('massive', 3168),
             ('easily', 8751),
             ('shared', 7591),
             ('between', 18654),
             ('two', 96390),
             ('portions', 18688),
             ('incredibly', 6952),
             ('affordable', 4955),
             ('giant', 5276),
             ('7', 23655),
             ('50', 22429),
             ('filled', 11763),
             ('checked', 13232),
             ('several', 27460),
             ('times', 68195),
             ('during', 31119),
             ('meal', 63888),
             ('definitely', 71364),
             ('bit', 67075),
             ('advice', 3971),
             ('ahead', 7816),
             ('prepared', 12606),
             ('atm', 1134),
             ('closed', 13023),
             ('sundays', 1710),
             ('mondays', 740),
             ('miss', 11168),
             ('stop', 24782),
             ('reviews', 34016),
             ('glad', 11938),
             ('busier', 764),
             ('nits', 1141),
             ('ages', 1502),
             ("you're", 52686),
             ('ambiance', 12179),
             ('bother', 6981),
             ('pretend', 875),
             ('movie', 8616),
             ('set', 17958),
             ('ago', 21601),
             ('works', 7891),
             ('girls', 14112),
             ('slow', 23937),
             ('few', 78982),
             ('different', 48611),
             ('check', 56856),
             ('made', 87044),
             ('fresh', 57425),
             ('nothing', 63010),
             ('comes', 25169),
             ('flying', 2086),
             ('kitchen', 20606),
             ('busy', 34082),
             ('food', 393384),

In [8]:
tokenizer.document_count

650000

In [9]:
sequences=tokenizer.texts_to_sequences(df_train['review_text'])

In [12]:
sequences

[[1048,
  42114,
  1447,
  198,
  5,
  266,
  10,
  11,
  4,
  1153,
  14087,
  1437,
  87,
  3,
  615,
  6,
  756,
  6,
  337,
  175,
  9767,
  1437,
  133,
  22,
  48,
  11,
  1015,
  197,
  3716,
  1437,
  10556,
  19,
  4,
  279,
  1562,
  2498,
  44886,
  64,
  15,
  1759,
  24,
  1126,
  6,
  36,
  13,
  42,
  1531,
  11,
  818,
  172,
  1804,
  3,
  21,
  230,
  3649,
  3,
  21,
  75,
  45,
  13981,
  6,
  152,
  13868,
  337,
  345,
  6,
  152,
  257,
  108,
  59,
  63,
  70,
  83,
  21,
  230,
  91,
  546,
  43,
  366,
  6,
  130,
  8,
  136,
  1472,
  5,
  24,
  56,
  257,
  16,
  91,
  59,
  8644,
  4,
  5730],
 [681,
  2,
  4645,
  8,
  175,
  1048,
  86981,
  1797,
  13,
  4,
  2231,
  8,
  2,
  143,
  112,
  25,
  19,
  28,
  195,
  81,
  3492,
  11,
  2608,
  31,
  1626,
  516,
  134,
  9,
  479,
  14,
  197,
  134,
  846,
  106,
  4149,
  2,
  507,
  9,
  373,
  870,
  114,
  378,
  8,
  4422,
  1616,
  6,
  45,
  62,
  1391,
  127,
  95,
  48,
  10,
  14,
  47,
  1718,
  6,
  414,
  19,
  9,
  5,
  24,
  574,
  183,
  18,
  478,
  19,
  195,
  81,
  3492,
  3,
  5,
  39,
  77,
  45,
  9,
  21,
  24,
  719,
  1404,
  21,
  24,
  3716,
  19,
  3210,
  644,
  235,
  397,
  525,
  4562,
  2,
  507,
  60,
  27441,
  3,
  23,
  231,
  2,
  12409,
  60,
  19,
  2398,
  14,
  5,
  244,
  14,
  5,
  24,
  6,
  160,
  1048,
  42114,
  114,
  212],
 [68,
  121,
  6,
  1048,
  42114,
  10,
  99,
  215,
  299,
  5,
  130,
  5,
  7,
  46,
  8,
  197,
  2204,
  3716,
  50,
  67,
  439,
  26,
  137848,
  1437,
  68,
  51,
  99,
  2,
  299,
  3,
  13,
  59,
  41,
  56,
  2,
  216,
  1445,
  9,
  13,
  74,
  8,
  257,
  23,
  15,
  174,
  3127,
  20222,
  1048,
  86982,
  14,
  5,
  267,
  38,
  5,
  24,
  76594,
  67,
  48507,
  41,
  489,
  19,
  21,
  3,
  13,
  42,
  1797,
  3,
  3258,
  67,
  401,
  2822,
  3,
  2633,
  41,
  2,
  147,
  1131,
  42,
  3698,
  3,
  1718,
  6,
  32,
  599,
  11,
  2,
  6730,
  22,
  208,
  3882,
  8,
  69,
  3210,
  1835,
  3,
  69,
  677],
 [78,
  4,
  3998,
  11,
  2,
  2425,
  194,
  423,
  14,
  113,
  1048,
  42114,
  13,
  1385,
  6,
  1397,
  6,
  156,
  4,
  166,
  4854,
  34,
  11,
  3942,
  67,
  71,
  32,
  1677,
  42,
  96,
  12,
  88,
  130,
  1477,
  4,
  166,
  1626,
  11,
  2608,
  14,
  21,
  245,
  37,
  435,
  330,
  32,
  35,
  766,
  35,
  366,
  6,
  189,
  4,
  895],
 [5,
  77,
  116,
  63,
  1048,
  42114,
  7,
  37,
  138,
  1385,
  6,
  1397,
  16,
  341,
  36,
  358,
  21,
  320,
  236,
  52,
  18,
  1626,
  3,
  18,
  719,
  5,
  7,
  121,
  6,
  1048,
  10670,
  138,
  67,
  232,
  3,
  42114,
  168,
  99,
  50,
  10670,
  232,
  67,
  13,
  23,
  4,
  3657,
  1626,
  67,
  13,
  66,
  1713,
  11,
  2,
  1646,
  289,
  3,
  345,
  21,
  125,
  11,
  10,
  5767,
  1581,
  208,
  819,
  67,
  71,
  23,
  160,
  1581,
  3,
  101,
  372,
  56,
  137849,
  6854,
  7679,
  366,
  6,
  45,
  69,
  1917,
  453,
  2425,
  236,
  3814,
  7348,
  300,
  18,
  381,
  13,
  4,
  1452,
  3,
  6,
  132,
  4103,
  79,
  888,
  197,
  719,
  134,
  13,
  4133,
  1917,
  8,
  2,
  48,
  50,
  21,
  335,
  2,
  719,
  2070,
  284,
  21,
  300,
  6,
  4,
  2643,
  2425,
  14,
  61,
  46,
  167,
  4149,
  47,
  4976,
  69,
  335,
  227,
  15,
  2449,
  1599,
  3,
  383,
  24,
  270,
  6,
  475,
  18,
  2508,
  86,
  5735,
  396,
  4645,
  2,
  590,
  719,
  95,
  62,
  898,
  37,
  20,
  29,
  547,
  21,
  4,
  1941,
  160,
  36,
  4,
  1176,
  320,
  236,
  52,
  18,
  7059,
  3,
  2,
  2508,
  21,
  2504,
  109,
  3,
  20,
  71,
  23,
  32,
  34,
  50,
  21,
  59,
  230,
  80,
  5,
  24,
  106,
  398,
  6305,
  6,
  892,
  4,
  137,
  286,
  56,
  525,
  385,
  5,
  1294,
  18,
  3563,
  1651,
  10,
  4,
  1626,
  127,
  13,
  41,
  56,
  2,
  273],
 [279,
  1562,
  1626,
  11,
  4,
  279,
  1562,
  2508,
  214,
  144,
  5,
  150,
  744,
  50,
  5,
  7,
  3863,
  6,
  257,
  76,
  164,
  1626,
  127,
  5,
  130,
  13,
  575,
  3,
  74,
  67,
  102,
  6,
  46,
  8,
  2,
  115,
  3210,
  9653,
  11,
  2,
  1468,
  733,
  13,
  59,
  615,
  6,
  45,
  62,
  840,
  34,
  13,
  3309,
  157,
  6,
  32,
  557,
  3,
  197,
  9130,
  2445,
  13,
  51],
 [1048,
  5840,
  42114,
  13,
  4,
  571,
  1626,
  127,
  95,
  2378,
  7917,
  208,
  788,
  14,
  15,
  481,
  3,
  5,
  24,
  25,
  2054,
  195,
  8,
  15,
  555,
  3492,
  1048,
  42114,
  13,
  42,
  4676,
  3,
  17,
  24,
  68,
  469,
  6,
  2016,
  3295,
  19,
  257,
  3,
  197,
  134,
  42,
  605,
  17,
  29,
  249,
  6,
  24,
  257,
  11,
  2,
  1072,
  3,
  266,
  949,
  6,
  175,
  197,
  3716,
  10,
  195,
  299,
  6,
  125],
 [91,
  1772,
  18,
  286,
  6,
  160,
  21,
  4,
  2796,
  49,
  138,
  21,
  152,
  18,
  1626,
  2,
  719,
  134,
  3,
  16352,
  29,
  42,
  1932,
  5,
  232,
  4,
  2360,
  19,
  1255,
  98,
  3072,
  15,
  510,
  3,
  61,
  46,
  167,
  277,
  36,
  58,
  5,
  25,
  6,
  10381,
  80,
  6,
  45,
  62,
  1391,
  56,
  15,
  510,
  12,
  3989,
  3,
  179,
  1531,
  132,
  169,
  69,
  1701,
  13,
  121,
  6,
  1206,
  1048,
  86981,
  1487,
  3,
  2346,
  231,
  67,
  917,
  6,
  36,
  14,
  5,
  45,
  4,
  5207,
  3,
  67,
  671,
  5,
  7,
  4,
  2559,
  74,
  5,
  161,
  257,
  5,
  78,
  2,
  5207,
  304,
  364,
  5,
  267,
  38,
  15,
  1835,
  1701,
  401,
  289,
  10,
  22241,
  1487,
  5,
  641,
  62,
  5047,
  611,
  510,
  10,
  2,
  2346,
  231,
  5,
  214,
  289,
  10,
  15,
  510,
  74,
  91,
  4,
  2559,
  3,
  77,
  24,
  136,
  945,
  4088,
  26,
  18,
  2664,
  48,
  5,
  214,
  584,
  2,
  1626,
  427,
  160,
  36,
  4,
  2796,
  49,
  6,
  132,
  169,
  15,
  1701,
  53,
  1206,
  231,
  14,
  155,
  2624,
  3,
  7,
  5360,
  22241,
  2,
  719,
  214,
  83,
  254,
  6,
  456,
  36,
  1206,
  2,
  510,
  11,
  1343,
  2,
  719,
  134,
  113,
  2,
  53239,
  13,
  22,
  36,
  6,
  132,
  169,
  15,
  1701,
  4056,
  1487,
  2882,
  1249],
 [2501,
  177,
  13,
  37,
  302,
  107,
  96,
  4,
  191,
  8,
  747,
  3,
  65,
  220,
  177,
  15932,
  467,
  220,
  255,
  2,
  374,
  582,
  29,
  31,
  520,
  3,
  752,
  16,
  10,
  209,
  4,
  2501,
  2,
  177,
  101,
  32,
  109,
  2,
  220,
  3,
  415,
  220,
  29,
  56,
  2,
  219,
  261,
  1125,
  2,
  371,
  263,
  13,
  31,
  3,
  13,
  4,
  321,
  665,
  880,
  29,
  288],
 [288,
  1434,
  1217,
  403,
  6,
  2,
  754,
  2,
  7291,
  29,
  107,
  1059,
  250,
  2,
  3487,
  1434,
  644,
  6,
  32,
  8850,
  84,
  60,
  37,
  3436,
  38,
  8,
  73,
  329,
  658,
  2900,
  23,
  42,
  29947,
  6,
  10873,
  64,
  285,
  8,
  12445,
  2,
  3120,
  8,
  121,
  6,
  4,
  2521,
  1434,
  146,
  609,
  148,
  212,
  74,
  2,
  1434,
  13,
  2436,
  49,
  26,
  129,
  64,
  13,
  350,
  10,
  309,
  8,
  73,
  127,
  29,
  5448,
  6,
  18,
  222,
  703,
  16,
  29,
  1217,
  558,
  22,
  48,
  345,
  4,
  484,
  886,
  1236,
  726,
  61],
 [13008,
  4,
  1422,
  1434,
  312,
  2,
  754,
  6679,
  13,
  37,
  4,
  3705,
  6,
  2794,
  273,
  5,
  77,
  130,
  5,
  282,
  96,
  38,
  8,
  4,
  1422,
  1434,
  288,
  7291,
  278,
  2071,
  3,
  4676,
  378,
  1171,
  21,
  230,
  79,
  372,
  98,
  174,
  19,
  2,
  32551,
  8,
  2,
  1209,
  14,
  56141,
  38,
  2,
  2071,
  18,
  33,
  95,
  717,
  8,
  80,
  9,
  13,
  3977,
  3,
  34,
  29,
  61,
  3487,
  12676,
  498,
  2723,
  20,
  758,
  10,
  2,
  2062,
  18,
  423,
  492,
  9,
  95,
  68,
  13929,
  1874,
  10,
  4,
  819,
  2,
  7291,
  266,
  37,
  2,
  1995,
  26,
  15,
  12721,
  445,
  256,
  5202,
  53240,
  362,
  3289,
  3,
  9271,
  3875,
  1384,
  756,
  56,
  2,
  378,
  18,
  33,
  13,
  6173,
  19,
  1479,
  498,
  20,
  66,
  1080,
  7834,
  8,
  2071,
  385,
  14365,
  9,
  13,
  146,
  600,
  38,
  333,
  2456,
  21,
  24,
  2,
  3154,
  6,
  645,
  183,
  50,
  5,
  441,
  5,
  155,
  169,
  40,
  18,
  7,
  4,
  1422,
  1434,
  47,
  62,
  86983,
  1905,
  10,
  4,
  103579,
  47,
  4,
  308,
  24035,
  4592,
  34,
  13,
  61,
  3487,
  22,
  2,
  1434,
  39,
  8615,
  477,
  9,
  4,
  31,
  6760,
  6,
  1374,
  38,
  123,
  347,
  21,
  245,
  29,
  3436,
  2,
  2029,
  448,
  20,
  29,
  945,
  66,
  85,
  12,
  3534,
  260,
  18,
  33,
  1236,
  2,
  115,
  743,
  13,
  14,
  2,
  504,
  3917,
  9,
  6,
  349,
  14,
  245,
  1718,
  6,
  132,
  273,
  3,
  54,
  14516,
  11,
  1408],
 [18,
  33,
  13,
  2048,
  2652,
  280,
  8,
  2,
  12676,
  29,
  23,
  666,
  820,
  41,
  2,
  3487,
  12676,
  9,
  13,
  945,
  66,
  3,
  20,
  1080,
  2,
  194,
  3639,
  26,
  487,
  1082,
  345,
  1479,
  3,
  40,
  21,
  902,
  79,
  4,
  753,
  86,
  487,
  77,
  1042,
  22,
  291,
  4,
  218,
  2,
  7442,
  1488,
  29,
  1609,
  38,
  8,
  419,
  3,
  20,
  1080,
  193,
  312,
  16,
  403,
  2,
  9792,
  26,
  487,
  22,
  2,
  8154,
  34,
  29,
  11752,
  3427,
  41,
  99,
  2,
  33,
  5,
  707,
  65,
  858,
  8,
  13009,
  6994,
  16,
  9,
  565,
  37,
  309,
  29,
  38,
  8,
  97,
  35,
  92,
  349,
  202,
  540,
  18,
  33,
  3,
  968,
  9,
  183,
  63,
  9,
  202,
  32],
 [5,
  1687,
  76,
  1553,
  6,
  45,
  4,
  6909,
  3115,
  9,
  1630,
  3599,
  22,
  2804,
  12855,
  3,
  5,
  214,
  157,
  6,
  156,
  15,
  476,
  2,
  166,
  1434,
  565,
  222,
  2,
  590,
  1434,
  2736,
  6,
  32,
  4883,
  64,
  418,
  47,
  195,
  23,
  456,
  69,
  703,
  16,
  9,
  565,
  59,
  87,
  2,
  5062,
  2411,
  266,
  1516,
  8,
  2,
  1474,
  3,
  2,
  491,
  362,
  565,
  37,
  172,
  684,
  152,
  22,
  4,
  3255,
  419,
  214,
  157,
  6,
  143,
  9],
 [86,
  336,
  10,
  330,
  334,
  142,
  6,
  3475,
  11,
  62,
  256,
  507,
  361,
  8,
  2,
  540,
  58,
  3117,
  44,
  252,
  54,
  3504,
  6012,
  4038,
  2,
  4391,
  18,
  3066,
  6,
  73,
  336,
  164,
  334,
  142,
  10,
  257,
  6,
  1511,
  9,
  77,
  281,
  18,
  241,
  40,
  21,
  139,
  876,
  47,
  31,
  54],
 [18,
  33,
  7,
  201,
  15,
  1759,
  442,
  4,
  1982,
  6,
  281,
  18,
  33,
  52,
  6164,
  103580,
  712,
  237,
  5,
  37,
  56,
  1408,
  3,
  1437,
  373,
  107,
  3999,
  197,
  2359,
  27,
  6,
  117,
  2,
  4750,
  371,
  263,
  3,
  329,
  5096,
  303,
  263,
  17,
  102,
  610,
  995,
  10,
  4,
  501,
  188,
  524,
  4,
  589,
  3,
  27,
  463,
  147,
  236,
  2,
  134,
  13,
  515,
  159,
  15,
  1016,
  5,
  310,
  25,
  2,
  371,
  263,
  163,
  15,
  2096,
  2145,
  25,
  4,
  4750,
  263,
  2,
  371,
  7,
  42,
  31,
  16,
  2,
  4750,
  7,
  6,
  1023,
  10,
  227,
  388,
  27,
  2225,
  3,
  101,
  42,
  1039,
  32,
  1175,
  578,
  122,
  98,
  22,
  279,
  8,
  175,
  515,
  321,
  577,
  9,
  7,
  1265,
  1641,
  2,
  1565,
  371,
  263,
  7,
  487,
  3,
  2,
  1565,
  4750,
  7,
  494,
  514,
  44,
  193,
  27,
  133,
  836,
  3,
  17,
  27,
  755,
  22,
  429,
  180,
  382,
  2,
  190,
  17,
  71,
  171,
  32,
  58,
  448,
  3,
  4,
  182,
  8,
  1916,
  1146,
  8,
  48,
  20,
  156,
  945,
  66,
  28,
  125,
  791,
  16,
  91,
  107,
  169,
  5,
  442,
  62,
  4336,
  34,
  35,
  92,
  3,
  5,
  83,
  584,
  20,
  29,
  764,
  22,
  3331,
  5628],
 [214, 867, 471, 10, 2, 115, 371, 263, 11, 1408],
 [18,
  33,
  202,
  24,
  4,
  191,
  70,
  355,
  16,
  91,
  831,
  9,
  401,
  20,
  77,
  230,
  6,
  45,
  136,
  5510,
  12,
  4322,
  68,
  34,
  3603,
  3,
  565,
  9,
  40,
  228,
  41,
  56,
  811,
  77,
  1257,
  40,
  21,
  5074,
  228,
  11,
  4,
  1051,
  591,
  11,
  1408,
  334,
  299,
  527,
  9,
  1134,
  107,
  92,
  2,
  54,
  13,
  726,
  645,
  47,
  867,
  179,
  8,
  725,
  29,
  31,
  46,
  13,
  42,
  488,
  46,
  13,
  222,
  20,
  29,
  41,
  159,
  3,
  373,
  4,
  154,
  243,
  98,
  71,
  213,
  11,
  6,
  132,
  169,
  14,
  228,
  249,
  198,
  13,
  140,
  211,
  28,
  32,
  791,
  14,
  192,
  465,
  2904,
  38,
  8,
  14,
  548,
  354,
  180,
  9,
  75,
  156,
  4,
  31,
  163,
  6,
  45,
  30,
  12,
  82,
  30,
  13,
  276,
  229,
  136,
  103,
  1472,
  5,
  435,
  130,
  49,
  138,
  9,
  609,
  34,
  269,
  206,
  22,
  2,
  153,
  5,
  1112,
  80,
  41,
  12,
  12,
  371,
  137850,
  12,
  760,
  318,
  3,
  201,
  12,
  12446,
  12,
  399,
  4,
  154,
  2196,
  69449,
  519,
  13,
  2400,
  10,
  15,
  234,
  3,
  5,
  106,
  25,
  9,
  3171,
  49,
  11,
  69449,
  12,
  64007,
  1702,
  272,
  12,
  1066,
  864,
  1273,
  10,
  122,
  685,
  9,
  12,
  82,
  242,
  29,
  749,
  2,
  577,
  29,
  321,
  3,
  39,
  56,
  198,
  22,
  2,
  124,
  13,
  201,
  91,
  23,
  46,
  6,
  561,
  4,
  33,
  74,
  20,
  160,
  21,
  4,
  191,
  8,
  30,
  16,
  40,
  21,
  37,
  4,
  31,
  951,
  3,
  77,
  139,
  6,
  10181,
  22,
  234,
  18,
  33,
  13,
  4,
  1877],
 [256,
  972,
  1306,
  1016,
  5807,
  1569,
  247,
  3,
  1814,
  2,
  115,
  371,
  3,
  490,
  684,
  167,
  412,
  3,
  2544,
  2460,
  313,
  399,
  4,
  51,
  38,
  8,
  2,
  119,
  570,
  2005,
  53241,
  8,
  13303,
  21,
  71,
  131,
  9],
 [31, 371, 263],
 [86,
  4,
  579,
  8,
  5568,
  241,
  7477,
  4,
  294,
  3,
  5,
  27,
  913,
  8,
  188,
  3,
  67,
  1605,
  86984,
  86,
  3525,
  557,
  2844,
  76595,
  83,
  4,
  182,
  22,
  9,
  3,
  25,
  223,
  9,
  4,
  48,
  47,
  122,
  138,
  3,
  5,
  25,
  23,
  67,
  113,
  20,
  25,
  4,
  288,
  4750,
  16,
  6,
  32,
  791,
  6,
  1414,
  58,
  11,
  48,
  12,
  2386,
  1015,
  35,
  123,
  91,
  285,
  8,
  5448,
  6,
  501,
  10925,
  3,
  610,
  7194,
  3,
  2,
  374,
  7060,
  2327,
  1720,
  6085,
  58,
  11,
  48,
  13,
  4,
  3575,
  587,
  11,
  3612,
  9193,
  35,
  196,
  35,
  9,
  401,
  10902,
  26749,
  64,
  5,
  75,
  152,
  41,
  149,
  36,
  208,
  151,
  12,
  1070,
  498,
  164,
  1002,
  26,
  1477,
  4,
  288,
  4750,
  11,
  3612,
  9193,
  92,
  239,
  37,
  7477,
  2,
  2825,
  16605,
  28,
  226,
  568,
  46,
  70,
  11625,
  932,
  427,
  2593,
  12,
  624,
  110,
  17,
  57,
  147,
  26,
  4490,
  11,
  2,
  740,
  8,
  184,
  813,
  27,
  17,
  26,
  108,
  5,
  246,
  17,
  27,
  919,
  1422,
  149,
  4,
  2730,
  8,
  42,
  509,
  8406,
  226,
  3029,
  11,
  63,
  275,
  37,
  4,
  1072,
  14,
  25,
  68,
  53242,
  76,
  2,
  1035,
  8,
  4,
  5603,
  3,
  105,
  27801,
  43,
  9,
  13,
  3,
  3913,
  34,
  9,
  7,
  18,
  103,
  7156,
  1035,
  19,
  62,
  678,
  22,
  1480,
  19,
  63,
  275,
  37,
  4,
  42,
  256,
  673,
  3640,
  697,
  3452,
  295,
  846,
  137851,
  12,
  259,
  390,
  11,
  2,
  292,
  411,
  3,
  2547,
  164,
  825,
  164,
  48,
  3,
  164,
  33,
  448,
  3,
  136,
  216,
  808,
  31395,
  6483,
  435,
  35,
  92,
  471,
  1117,
  174,
  5,
  427,
  139,
  6,
  152,
  21,
  391,
  11,
  521,
  69,
  1368,
  3,
  144,
  137852,
  2761,
  12,
  543,
  13,
  56,
  35,
  256,
  825,
  128,
  1115,
  104,
  35,
  9,
  609,
  1097,
  19,
  4,
  868,
  2006,
  128,
  22,
  46,
  210,
  1097,
  573,
  1291,
  19,
  61,
  25859,
  3597,
  31,
  12722,
  1052,
  3,
  1183,
  573,
  6583,
  22,
  2,
  352,
  18,
  13,
  2,
  285,
  8,
  1072,
  1974,
  14,
  5,
  101,
  152,
  4472,
  3,
  23305,
  4025,
  4,
  154,
  352,
  746,
  10,
  65,
  2775,
  4,
  371,
  10671,
  3,
  65,
  424,
  5253,
  3,
  14,
  13,
  813,
  63,
  5,
  131,
  12,
  1742,
  16,
  31,
  30,
  7207,
  84,
  12,
  259,
  310,
  25,
  4,
  4750,
  3,
  15,
  294,
  25,
  4,
  210,
  8,
  238,
  2,
  23306,
  27,
  288,
  16,
  23,
  1673,
  276,
  4,
  103,
  84,
  1028,
  22,
  2,
  287,
  16,
  431,
  316,
  3,
  171,
  1074,
  23,
  84,
  4167,
  22,
  2,
  253,
  5,
  647,
  3396,
  4,
  1027,
  31,
  1673,
  4750,
  16,
  165,
  5,
  214,
  2790,
  6,
  1980,
  147,
  174,
  63,
  5,
  189,
  11,
  3612,
  9193,
  71,
  24,
  6,
  83,
  16,
  35,
  17,
  452,
  3,
  512,
  581,
  100,
  38,
  6,
  62,
  7903,
  153,
  309,
  27,
  65,
  216,
  1028,
  581,
  4,
  303,
  102,
  555,
  10,
  2,
  153,
  625,
  73,
  14,
  7,
  318,
  3,
  50,
  17,
  162,
  56,
  9,
  2,
  306,
  113,
  31951,
  60,
  318,
  3,
  59,
  31,
  3,
  67,
  66,
  2046,
  651,
  837,
  10,
  9,
  3381,
  14,
  2534,
  2761,
  164,
  153,
  8,
  730,
  100,
  11,
  3,
  29015,
  371,
  682,
  4491,
  19,
  3104,
  371,
  14,
  275,
  222,
  976,
  5,
  139,
  14,
  14,
  14,
  3,
  14,
  12,
  440,
  294,
  85,
  985,
  14,
  20,
  24,
  4,
  118,
  3589,
  272,
  46,
  151,
  8,
  2,
  423,
  14,
  13,
  66,
  353,
  385,
  204,
  1154,
  3,
  14,
  9,
  13,
  571,
  40,
  66,
  5,
  101,
  45,
  34,
  22,
  14,
  423,
  151,
  138,
  204,
  12,
  82,
  306,
  94,
  4,
  31,
  484,
  420,
  165,
  34,
  7,
  295,
  4,
  3171,
  737,
  26,
  4490,
  22,
  4,
  589,
  3,
  66,
  46,
  8,
  120,
  72,
  599,
  49,
  3,
  7,
  42,
  159,
  12,
  629,
  66,
  24,
  5376,
  1260,
  28,
  5,
  25,
  4,
  5023,
  1334,
  513,
  64,
  7,
  42,
  211,
  3,
  72,
  94,
  1569,
  76,
  6,
  282,
  56,
  1581,
  35,
  656,
  35,
  72,
  101,
  35,
  2,
  188,
  224,
  102,
  22,
  20,
  27,
  291,
  354,
  12,
  137853,
  13,
  61,
  4870,
  31,
  577,
  42,
  694,
  242,
  42,
  735,
  1072,
  1515,
  11,
  2,
  850,
  285,
  8,
  37,
  5731,
  16,
  11,
  4,
  1019,
  6962,
  1072,
  11,
  2,
  15995,
  506,
  5416,
  13869,
  5,
  101,
  244,
  26,
  240,
  43,
  12,
  1538,
  171,
  139,
  6,
  645,
  31396,
  47,
  5622,
  11,
  69,
  6514,
  176,
  5,
  150,
  23,
  169,
  14,
  5,
  101,
  189,
  9,
  111,
  22,
  15,
  444,
  9,
  59,
  13,
  4,
  1799,
  1877,
  5,
  71,
  32,
  556,
  15,
  294,
  156,
  36,
  58,
  385,
  5,
  75,
  20096,
  184,
  2,
  2199,
  9,
  13,
  12,
  29948,
  1709,
  281,
  10,
  2,
  371,
  263,
  350,
  1011,
  4,
  2576,
  8,
  371,
  22,
  4,
  371,
  3906,
  1141,
  35,
  3937,
  6,
  3612,
  103581,
  4281,
  1546,
  2455,
  1141,
  2,
  371,
  7,
  865,
  2,
  2322,
  350,
  3,
  10,
  39,
  487,
  18,
  418,
  24,
  68,
  2,
  115,
  371,
  263,
  112,
  498,
  6,
  24,
  11,
  3612,
  9193],
 [4,
  51,
  27802,
  128,
  19,
  316,
  30,
  3,
  62,
  804,
  2862,
  5,
  102,
  6,
  213,
  18,
  33,
  38,
  22,
  2,
  119,
  240,
  52,
  2,
  908,
  46,
  708,
  129,
  3,
  9,
  89,
  2286,
  9,
  13,
  1918,
  6,
  391,
  183,
  4,
  27802,
  128,
  3,
  23,
  244,
  37,
  2,
  402,
  3528,
  3,
  368,
  11,
  2,
  33,
  13,
  3456,
  26,
  21,
  91,
  3431,
  2,
  930,
  737,
  8,
  1320,
  4441,
  2124,
  979,
  1830,
  11,
  15205,
  2381,
  3,
  69450,
  24,
  251,
  557,
  9,
  41,
  382,
  55,
  48,
  26,
  18,
  33,
  12,
  82,
  134,
  7,
  279,
  1562,
  2,
  675,
  27,
  1217,
  2676,
  35,
  20,
  1875,
  558,
  3560,
  10,
  2,
  129,
  16,
  15,
  306,
  223,
  6,
  459,
  4,
  1276,
  898,
  10,
  15,
  590,
  281,
  2,
  81,
  386,
  7,
  2014,
  4,
  42115,
  23764,
  3,
  5,
  203,
  6,
  3324,
  9,
  52,
  257,
  692,
  6,
  15,
  6872,
  11,
  1477,
  396,
  4,
  247,
  7956,
  8,
  2337,
  12,
  259,
  90,
  4,
  573,
  173,
  321,
  11,
  520,
  24284,
  11,
  170,
  283,
  8,
  691,
  261,
  865,
  220,
  871,
  62,
  431,
  201,
  173,
  1809,
  52,
  114,
  237,
  209,
  119,
  84,
  96,
  2008,
  5,
  116,
  18,
  465,
  19,
  2,
  9913,
  16,
  146,
  9,
  13,
  726,
  7502,
  114,
  2679,
  1138,
  2,
  451,
  185,
  6,
  125,
  38,
  8,
  4,
  75,
  167,
  5,
  53,
  509,
  158,
  2679,
  42116,
  93,
  2679,
  1138,
  3,
  40,
  2,
  1138,
  593,
  2679,
  20,
  27,
  39,
  2,
  451,
  1138,
  112,
  167,
  5625,
  2,
  1446,
  11280,
  13,
  225,
  6,
  1750,
  2,
  286,
  76,
  62,
  590,
  311,
  1243,
  12,
  440,
  1916,
  10,
  2,
  33,
  13,
  459,
  198,
  276,
  1846,
  402,
  52,
  2,
  6287,
  316,
  30,
  51,
  242,
  31,
  737,
  3,
  134,
  3,
  45,
  65,
  288,
  1138,
  235,
  20,
  8755,
  62,
  1057,
  872,
  486,
  1009,
  19,
  396,
  9341,
  1292,
  356,
  106,
  116],
 [31,
  274,
  317,
  3562,
  10,
  4,
  600,
  1394,
  129,
  737,
  9,
  155,
  120,
  1473,
  72,
  7,
  2,
  66,
  233,
  16,
  9,
  168,
  56,
  62,
  224,
  6,
  45,
  44,
  682,
  899,
  7,
  46,
  8,
  2,
  115,
  23306,
  112,
  167,
  25],
 [42,
  348,
  11,
  2,
  252,
  54,
  17,
  90,
  21497,
  3,
  203,
  2764,
  394,
  8,
  13982,
  20,

In [37]:
from tensorflow.keras.utils import pad_sequences

In [38]:
sequences=pad_sequences(sequences,padding='post')

In [39]:
len(sequences)

650000

In [68]:
df_test=pd.read_csv("YELP SA/yelp_review_fine-grained_5_classes_csv/test.csv")
df_test

       class_index                                        review_text
0                1  I got 'new' tires from them and within two wee...
1                1  Don't waste your time.  We had two different p...
2                1  All I can say is the worst! We were the only 2...
3                1  I have been to this restaurant twice and was d...
4                1  Food was NOT GOOD at all! My husband & I ate h...
...            ...                                                ...
49995            1  Just wanted to write a review to chip in with ...
49996            5  Great ambience. Great drinks. Great food. I lo...
49997            4  I have been to the other Monks locations so I ...
49998            2  Don't go here.  I know you might want to try i...
49999            1  Buffet was recently open after renovation so m...

[50000 rows x 2 columns]

In [76]:
X_test=df_test['review_text']
X_test
tokenizer.fit_on_texts(X_test)
tokenizer.word_index

SyntaxError: invalid syntax (997648460.py, line 1)

In [77]:
test_sequences=tokenizer.texts_to_sequences(X_test)

In [78]:
test_sequences=pad_sequences(test_sequences,padding='post')

In [79]:
X_test=test_sequences

In [80]:
y_test=df_test["class_index"]

In [40]:

X_train=sequences

In [41]:
y_train=df_train["class_index"]

In [93]:
y_train=y_train -1

In [94]:
y_test=y_test -1

In [95]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [96]:
model1=Sequential()

In [97]:
X_train.shape

(650000, 1047)

In [98]:

y_train.shape

(650000,)

In [99]:
import numpy as np

# This adds a 3rd dimension so the shape becomes (650000, 1047, 1)
X_train_rnn = X_train.reshape((X_train.shape[0], X_train.shape[1], 1))

In [100]:
model1.add(SimpleRNN(32,input_shape=(1047,1),return_sequences=False))
model1.add(Dense(5,activation='softmax'))
model1.summary()

D:\devan\JetBrains\PyCharm\projects\.venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_8 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 5)              │           165 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,253 (4.89 KB)

 Trainable params: 1,253 (4.89 KB)

 Non-trainable params: 0 (0.00 B)

In [101]:
model1.weights

[<Variable path=sequential_6/simple_rnn_8/simple_rnn_cell/kernel, shape=(1, 32), dtype=float32, value=[[ 0.05437303  0.23794091 -0.03153902  0.16101557  0.291426    0.06697717
    0.3571025  -0.34707618  0.05286506  0.3742661  -0.24411035 -0.04206622
   -0.27081168 -0.08308533 -0.05471796 -0.37330803  0.41676176 -0.2525486
    0.28414965 -0.25641328 -0.23506303  0.20413339  0.26213306  0.08762461
   -0.02391997 -0.18818404  0.41758013 -0.38681617  0.13407612 -0.29291308
   -0.34239385 -0.05457726]]>,
 <Variable path=sequential_6/simple_rnn_8/simple_rnn_cell/recurrent_kernel, shape=(32, 32), dtype=float32, value=[[ 0.04323196 -0.15731192  0.28324273 ...  0.05710457 -0.06621794
   -0.12242231]
  [-0.04365899 -0.0984454  -0.3414118  ...  0.45557153  0.10511619
   -0.07034642]
  [ 0.01779122  0.00871411  0.03088175 ...  0.04224655 -0.15968929
   -0.12272897]
  ...
  [ 0.05326667  0.00053022  0.10638975 ...  0.09327607  0.43203583
    0.1832253 ]
  [-0.02123928  0.14473999  0.1610239  ...  0.00344161  0.04256341
   -0.2924836 ]
  [ 0.22787525  0.0312415   0.12454557 ...  0.04215775 -0.02111246
   -0.29569274]]>,
 <Variable path=sequential_6/simple_rnn_8/simple_rnn_cell/bias, shape=(32,), dtype=float32, value=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]>,
 <Variable path=sequential_6/dense_6/kernel, shape=(32, 5), dtype=float32, value=[[ 0.101758   -0.23766352  0.21683395  0.36778206  0.10262823]
  [ 0.04642615 -0.03665552  0.33882976 -0.24749653 -0.29589614]
  [-0.3854478  -0.28534296 -0.31591243 -0.39703107 -0.39516044]
  [ 0.0598864   0.03627416  0.15294099  0.12405658  0.00973201]
  [ 0.12195885 -0.10465857 -0.25226188  0.23650122 -0.13933802]
  [-0.28046384  0.18462509 -0.35597494  0.38258928  0.28483582]
  [ 0.36040467  0.22229832  0.07249284  0.2016406   0.06962544]
  [-0.27083763 -0.27837008 -0.3934748   0.36826158  0.08451959]
  [-0.28891492 -0.10699707  0.28005272  0.2145319  -0.07700962]
  [ 0.3663975   0.35017473  0.19589078 -0.04661039  0.09027988]
  [-0.33607408  0.33991015 -0.3971577  -0.18357821 -0.34999892]
  [ 0.25131243 -0.05365959 -0.24272083  0.26913512 -0.06280863]
  [-0.09862715  0.29213518  0.37631422 -0.294437    0.27289551]
  [ 0.21580327  0.01322725  0.37038034  0.15016347  0.20568532]
  [-0.18597163 -0.16503693 -0.36438596 -0.39165905  0.3275361 ]
  [ 0.02746192  0.2733379  -0.23123461  0.14908731 -0.03090617]
  [-0.40161785 -0.22945824  0.15103823  0.00487575 -0.35339797]
  [-0.13079384  0.16712773 -0.11378324  0.30276775 -0.25958002]
  [ 0.2570781   0.263165    0.23229265  0.36818165  0.1636135 ]
  [ 0.22304845  0.1708821   0.24393594  0.10295212  0.3840646 ]
  [-0.14797333  0.21384043  0.29693317 -0.23291133  0.07708949]
  [ 0.28381658  0.21594948  0.09019348 -0.10609421  0.18720245]
  [-0.34979922  0.21613806 -0.2858767   0.19665015  0.3498813 ]
  [ 0.34190524 -0.34718737  0.06991613  0.23478699  0.36978722]
  [ 0.06301469 -0.16435479 -0.35128403 -0.24951582  0.29462683]
  [ 0.00312376  0.34570497  0.33066952 -0.32293725  0.34028804]
  [-0.25061446 -0.33729476 -0.27274612  0.21534532 -0.31653795]
  [ 0.2192412  -0.1821804  -0.17718196 -0.39663368 -0.24088791]
  [ 0.15775949  0.03697312  0.13266432  0.28420562 -0.38949105]
  [ 0.24904472  0.26093328  0.27268773  0.01109478  0.09500518]
  [-0.37454426  0.2555158   0.3498695   0.37692404  0.24082655]
  [ 0.33752602  0.23114991 -0.09338099  0.08836421 -0.16447787]]>,
 <Variable path=sequential_6/dense_6/bias, shape=(5,), dtype=float32, value=[0. 0. 0. 0. 0.]>]

In [102]:
model1.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:

model1.fit(X_train_rnn,y_train,epochs=10,batch_size=32,validation_data=(X_test,y_test))

Epoch 1/10
 4818/20313 ━━━━━━━━━━━━━━━━━━━━ 8:53 34ms/step - accuracy: 0.1996 - loss: 1.6125